### ISSUE TITLE
Bug on API?

### ISSUE THREAD

**Issue by rdemeyer** [mauserrifle/simresults#56]
Hello,

I try to use the API for grouping the result of my league (on R3E). For that purpose, I created a JSON as described in your docs:
http://ec2-35-180-32-180.eu-west-3.compute.amazonaws.com/results/json/simresult.json

Seems to work well : http://simresults.net/remote?results=http%3A%2F%2Fec2-35-180-32-180.eu-west-3.compute.amazonaws.com%2Fresults%2Fjson%2Fsimresult.json

Unfortunately, it does not work well at the moment because, if I update my json input file, for example by adding a new event, this event does not appear in the dropdown list when I refresh the page in simresults (while I can see the change in my webserver). Finally, I'll see this event a few hours later (which is problematic as our drivers want to see the results just after the race).

Seems that there is some caching or something?

I also notice that when I select one event and then an other in the dropdown, there is a duplicated parameter in the URL : "&result=4&result=11". This bug is also visible when using the demo in your API description page : http://simresults.net/remote?results=http%3A%2F%2Fsimresults.net%2Fexample.json&result=1&result=0

Maybe is those two issue related with each other?

Thanks in advance for your support,

BR

PS : there is also another bug in raceroom, all names are now "broken" : John D instead of John Doe (only when using manual upload, not through the API)

**Comment by mauserrifle** [comment]
Hi rdemeyer,

I have not had time yet to look into the API issue and fix it. But you might be able to workaround the cache by adding the following to the end of your json URL:
%3Fversion%3D1
%3Fversion%3D2
%3Fversion%3D3 

Thus increasing a query parameter `?version=1`.

The issue about names missing parts is because of new default privacy settings. I had too much complaints about privacy. If you don't mind full names, please look at the "Customize" tab on the website and de-select shortening surnames. But it's best to always check with your drivers that give you permission.

**Comment by rdemeyer** [comment]
Hi mauserrifle,

Perfect, your query parameter trick worked perfectly, awesome, thanks.

And ok also for the shorten names, I missed that! Thanks again

**Comment by mauserrifle** [comment]
Hi rdemeyer,

i just updated the api documentation page:
https://simresults.net/api

It now includes information about cache invalidation and I also added the option to customize results (such as privacy options).

Cheers,
Maurice
