### ISSUE TITLE
Project Cars 2: Player not being recognized as the same user across two races.

### ISSUE THREAD

**Issue by tylerjw** [mauserrifle/simresults#57]
I'm using your website to calculate the points for our league and it is showing one of our players as being a separate user across two races.  Here is a link to the result:

https://simresults.net/181018-4Jj

If it would be useful I can attach the logfiles I used to create this result.  You can see that the player 'V8_Fiero' is listed twice on the points breakdown and is in both race 2 and 3.  We are using the MotoGP points schedule. 

One thing to note is that I entered each race as a separate json file.  We run two races a week and I removed all the other history results from each file so it only contained one practice/qual/race session.

**Comment by mauserrifle** [comment]
Hi tylerjw,

Sorry for the very late response! But better very late than never :)

This issue has been resolved. It was caused by the fact that in one result the driver had a driver id (steam id) and in other result it did not. I still need to reply on steam id too because sometimes drivers change their name. I made a last resort fix that scans all points entries en fixes any duplicates.

Thank you for reporting!

Cheers,
Maurice
