### ISSUE TITLE
ACC: import driver class (cupCategory) from results

### ISSUE THREAD

**Issue by wakcs** [mauserrifle/simresults#71]
Hi, I have a request that hopefully isn't too much of a hassle.

Adding support for ACC's CupCategory property from the result JSON
![notepad++_qavNEnSDF2](https://user-images.githubusercontent.com/6357156/99734005-5dc2c680-2ac2-11eb-9cd5-26736f8d3d47.png)

**Cup Categorys**

- 0 = Overall
- 1 = ProAm
- 2 = Am
- 3 = Silver
- 4 = National

Cheers :)

**Comment by wakcs** [comment]
Have given it a go myself https://github.com/mauserrifle/simresults/pull/73

**Comment by mauserrifle** [comment]
Great! I merged it with some additions:

* Added tests
* Fixed undefined index error
* Made the code more defensive so it less likely to fail (like missing cupCategory in json)

Thanks for your work!

**Comment by mauserrifle** [comment]
FYI. This functionality has been changed. When updating the library please use `Vehicle::getCup()` instead. I had to move this away from `getClass` because the parser now parses the GT3/GT4 classes for proper result splitting on the website. 

Details at commit:
https://github.com/mauserrifle/simresults/commit/f6447c36ac6729c2bc05c8331b1b4c9a077cdd9b
