### ISSUE TITLE
PC2 Final Race Position Issue

### ISSUE THREAD

**Issue by simracing** [mauserrifle/simresults#77]
Hi Maruice,
I wanted to pass this along.  We had a PC2 event and it incorrectly scored a driver.   I've attached the result file.   In the Race3 session driver Stefan S finished 5th but Simresults reported him finishing 7th.

Again we thank you for you hard work in maintaining this awesome repo!
SRO

[PC2 XBow GT4 Algarve sms_stats_data.zip](https://github.com/mauserrifle/simresults/files/6331661/PC2.XBow.GT4.Algarve.sms_stats_data.zip)

**Comment by mauserrifle** [comment]
Thanks for reporting! Wow I can't believe I did not spot this issue myself since my initial logs have the same issue. This bug exists since 2016.

Project Cars writes a final result array (order of finish). But in this case the driver Stefan was missing from this array. I created a fix that checks whether all finished drivers (from lap events) are in the final results array, if so then I use it, if not then I will fallback to old fashioned sorting. 

Even though this way the total time of the participant will be the total of all laps instead of the total time project cars reports. I could set the total time for the drivers in the final results array, but it means the missing driver will not have this time and we will have bad driver sorting once again.

So it's not a perfect fix but I think it is the best I can do.

https://github.com/mauserrifle/simresults/commit/0ea44f1604668f965ef847f585bde5f94963246f
